version: '3'
services:
  book-keeper-nginx:
    depends_on:
      - book-keeper-backend
      - book-keeper-client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3002:3002'

  book-keeper-backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file: .env

  book-keeper-client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client

networks:
  default:
    external:
      name: droplet-proxy
# Port configuration
# book-keeper-nginx:3002 ---> book-keeper-backend:8002
# book-keeper-nginx:3002 ---> book-keeper-client:5002
