version: "3"
services:
  book-app-nginx:
    depends_on:
      - backend
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3002:3002"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file: .env

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client

networks:
  default:
    external:
      name: nginx-proxy
