spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/authentication?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${OAUTH2_REDIRECT_URL_PROD}
            scope:
              - profile
              - email
          github:
            clientId: ${GITHUB_CLIENT_ID_PROD}
            clientSecret: ${GITHUB_CLIENT_SECRET_PROD}
            redirectUri: ${OAUTH2_REDIRECT_URL_PROD}

oauth2:
  successUrl: http://128.199.13.150:80
  failureUrl: http://128.199.13.150:80/login-error
